### ISSUE TITLE
Satis doesn't deliver dev-master package

### ISSUE THREAD

**Issue by waldo2188** [composer/satis#144]
Hi,

I've a little issue. I don't know if it's a bug or a misconfiguration.
I've configure Satis for retrieve the dev branch of packages.
Like this :

``` yaml
{
    "repositories": [
        { "type": "composer", "url": "https://packagist.org" }
    ],

    "require-all": false,

    "require": {
        "doctrine/doctrine-fixtures-bundle": ">=0.1"
    },

    "require-dependencies": true,

    "archive": {
        "directory": "dist",
        "format": "tar",
        "skip-dev": false
    }
}
```

But when I run a composer install/update in my Sf2 project, composer try to clone 
 doctrine/doctrine-fixtures-bundle (dev-master ccd69d9) from github and don't retrieve from Satis.
For the dependecies who aren't dev-master, all work fine.

The composer.json from my project as this config :

``` yaml
"require": {
        "doctrine/doctrine-fixtures-bundle": "dev-master"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://172.16.20.110"
        },        
        {
        "packagist": false
        }
    ]
```

Did I miss something ?
