### ISSUE TITLE
Branch alias

### ISSUE THREAD

**Issue by trsteel88** [composer/satis#52]
Is satis meant to retrieve the branch aliases?

I have the following:

``` yaml
"extra": {
    "branch-alias": {
        "dev-master": "1.0-dev"
    }
}
```

However, when I put "1.0.*" or "1.0-dev" etc in my application it does not recognise the version.
