### ISSUE TITLE
ErrorException: copy(/tmp/composer_archive60e5622111255.tar): Failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by hannius** [composer/satis#655]
Hello,
I've deployed a satis instance using the satis.json from k8s :
1、the configmap file is below:
```
apiVersion:` v1
kind: ConfigMap
metadata:
  name: satis-config-cm
  namespace: martin-test
data:
  satis.json: |-
    {
        "name": "martin/composer-repository",
        "homepage": "https://satis.martin.com",
        "require": {
            "guzzlehttp/guzzle": "^6.5",
            "illuminate/redis": "5.7.*",
            "jenssegers/mongodb": "3.4.*",
            "laravel/lumen-framework": "5.7.*",
            "lcobucci/jwt": "^3.3",
            "overtrue/socialite": "^2.0",
            "predis/predis": "^1.1",
            "ramsey/uuid": "^3.9",
            "vlucas/phpdotenv": "~2.2",
            "fzaninotto/faker": "~1.4",
            "mnabialek/laravel-sql-logger": "^2.2",
            "mockery/mockery": "~1.0",
            "phpunit/phpunit": "~7.0",
            "yiisoft/yii2": ">=2.0.13",
            "yiisoft/yii2-bootstrap": "*",
            "yiisoft/yii2-swiftmailer": "*",
            "feehi/yii2-swoole": ">=0.0.5",
            "feehi/yii2-cdn" : "*",
            "yiisoft/yii2-imagine": "^2.1",
            "qcloudsms/qcloudsms_php": "0.1.*",
            "kartik-v/yii2-widget-select2": "@dev",
            "moonlandsoft/yii2-phpexcel": "*",
            "kartik-v/yii2-export":"*",
            "kartik-v/yii2-widget-datetimepicker":"*",
            "kartik-v/yii2-date-range":"dev-master",
            "yiisoft/yii2-redis": "^2.0",
            "sizeg/yii2-jwt": "^2.0",
            "yiisoft/yii2-queue": "^2.3",
            "yiisoft/yii2-debug": "~2.0.0",
            "yiisoft/yii2-gii": "~2.0.0",
            "yiisoft/yii2-faker": "~2.0.0",
            "codeception/base": "^2.2.3",
            "codeception/verify": "~0.3.1",
            "guzzlehttp/guzzle": ">=4.1.4 <7.0",
            "fxp/composer-asset-plugin": "*",
            "bower-asset/yii2-pjax": "~2.0.1",
            "bower-asset/typeahead.js": "0.10.* | ~0.11.0",
            "bower-asset/punycode": "1.3.*",
            "bower-asset/jquery": "3.4.*",
            "bower-asset/inputmask": "~3.2.2 | ~3.3.5",
            "bower-asset/bootstrap": "3.4.* | 3.3.* | 3.2.* | 3.1.*",
            "encore/laravel-admin": "1.6.13",
            "fideloper/proxy": "~3.3",
            "intervention/image": "^2.5",
            "laravel/framework": "5.5.*",
            "laravel/tinker": "~1.0",
            "maatwebsite/excel": "2.1.30 | 3.0.1 | 3.1.10 | 3.1.15 | 3.1.16 | 3.1.17",
            "nesbot/carbon": "^1.29.1",
            "qcloud/cos-sdk-v5": "2.0.3",
            "filp/whoops": "~2.0",
            "symfony/thanks": "^1.0",
            "tencentcloud/tencentcloud-sdk-php": ">=3.0.400 < 3.0.410",
            "tymon/jwt-auth": "^1.0",
            "php-ffmpeg/php-ffmpeg": "^0.18.0"
        },
        "archive": {
            "directory": "dist",
            "format": "tar",
            "prefix-url": "https://satis.martin.com",
            "skip-dev": true
        },
        "require-all": false,
        "require-dependencies": true,
        "require-dev-dependencies": true,
        "repositories": [
            { "type": "composer", "url": "https://mirrors.aliyun.com/composer/" },
            { "type": "composer", "url": "https://asset-packagist.cn" }
        ]
    }
```

and i have deployed the satis pod using the persistent  volumn that is the way of hostpath

2、the deployment file is below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satis-app
  namespace: martin-test
  labels:
    app: satis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satis-app
  template:
    metadata:
      labels:
        app: satis-app
    spec:
      hostAliases:
      - ip: "10.0.3.90"
        hostnames:
        - "git.martin.com"
      - ip: "10.0.3.40"
        hostnames:
        - "satis.martin.com"
      containers:
        - name: composer
          image: composer/satis:latest
          #imagePullPolicy: Always
          workingDir: /build
          volumeMounts:
          - name: build-data
            mountPath: /build/output
          - name: satis-config-cm
            mountPath: /build/satis.json
            subPath: satis.json
          - name: satis-composer-cm
            mountPath: /composer/composer.json
            subPath: composer.json
          env:
            - name: TZ
              value: "Asia/Shanghai"
        - name: nginx
          image: "nginx:1.17.9"
          #imagePullPolicy: Always
          workingDir: /etc/nginx/conf.d
          env:
            - name: TZ
              value: "Asia/Shanghai"
          volumeMounts:
          - mountPath: /data/wwwroot/satis
            name: build-data
          - mountPath: /etc/nginx/conf.d/ 
            name: satis-nginx-cm
          - mountPath: /data/logs/nginx
            name: satis-logs-pvc
            #subPath: nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
      - name: qcloudregistrykey
      - name: tencenthubkey
      volumes:
      - name: build-data
        #emptyDir: {}
        #persistentVolumeClaim:
        #  claimName: satis-data-pvc
        hostPath:
          #path: /var/lib/docker/satis_data_modify
          path: /var/lib/docker/satis_data
      - name: satis-logs-pvc
        emptyDir: {}
      - name: satis-nginx-cm
        configMap:
          name: satis-nginx
      - name: satis-config-cm
        configMap:
          name: satis-config-cm
      - name: satis-composer-cm
        configMap:
          name: satis-composer-cm
      nodeSelector:
        satis: "true"
```

but when the pod is running, i find the error logs:
![image](https://user-images.githubusercontent.com/18302266/124731759-1c920080-df45-11eb-8655-a4834b0c093d.png)

could you help me to solve the problem, thanks very much!

**Comment by kluvi** [comment]
I have similar error with similar deployment:

docker-compose:
```
version: '3'

services:
  satis:
    image: composer/satis
    volumes:
      - ./docker-data/build:/build
      - ./satis.json:/build/satis.json
      - ./ssh-keys:/root/.ssh
      - ./docker-data/satis-composer:/composer
      - ./auth.json:/composer/auth.json
```

satis.json:
```
{
  "name": "zzz/www",
  "homepage": "https://XXXX",
  "repositories": [
    { "type": "vcs", "url": "git@gitlab.com:xxx/yyy.git" }
  ],
  "require": {
    "xxx/yyy": "*"
  },
  "require-all": false,
  "require-dependencies": false,
  "require-dev-dependencies": false,
  "archive": {
    "directory": "dist",
    "skip-dev": true,
    "prefix-url": "https://XXXX",
    "checksum": false
  }
}
```

The problem appers somewhere from 2021-07-02 13:30:00 (GMT+0200) (our last successfull build)
